- id: '1764873053414'
  alias: Surveillance Congélateur consommation
  description: Si la consommation est en dessous de 50W envoie une notifications sur
    le natel à Adrien
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.swiss_domotique_plug_576073_power
    for:
      hours: 1
      minutes: 0
      seconds: 0
    below: 50
  conditions: []
  actions:
  - action: notify.mobile_app_ipad
    metadata: {}
    data:
      title: 'ATTENTION '
      message: Congélateur BAHU ou Adrien ne fonctionne plus
  - action: notify.mobile_app_pixel_10_pro_xl
    metadata: {}
    data:
      message: Congélateur BAHU ou Adrien ne fonctionne plus
      title: ATTENTION
  mode: single
- id: '1767541801466'
  alias: Energy - Peak matin
  description: ''
  triggers:
  - at: 07:00:00
    trigger: time
  actions:
  - target:
      entity_id:
      - select.energy_daily
      - select.energy_monthly
      - select.energy_quarterly
      - select.energy_yearly
    data:
      option: peak
    action: select.select_option
  mode: single
- id: '1767541918933'
  alias: Energy - Peak midi
  description: ''
  triggers:
  - at: '12:00:00'
    trigger: time
  actions:
  - target:
      entity_id:
      - select.energy_daily
      - select.energy_monthly
      - select.energy_quarterly
      - select.energy_yearly
    data:
      option: peak
    action: select.select_option
  mode: single
- id: '1767541948084'
  alias: Energy - Peak soir
  description: ''
  triggers:
  - at: '17:00:00'
    trigger: time
  actions:
  - target:
      entity_id:
      - select.energy_daily
      - select.energy_monthly
      - select.energy_quarterly
      - select.energy_yearly
    data:
      option: peak
    action: select.select_option
  mode: single
- id: '1767541969067'
  alias: Energy - Peak nuit
  description: ''
  triggers:
  - at: '23:00:00'
    trigger: time
  actions:
  - target:
      entity_id:
      - select.energy_daily
      - select.energy_monthly
      - select.energy_quarterly
      - select.energy_yearly
    data:
      option: peak
    action: select.select_option
  mode: single
- id: '1767729134959'
  alias: Surveillance congélateur
  description: Si la puissance est inférieure à 20W pendant plus de 1h
  triggers:
  - type: power
    device_id: be60e7da4fe8ba268c769dea49a1a863
    entity_id: 034b305d30164a36a3660886302e057f
    domain: sensor
    trigger: device
    below: 20
    for:
      hours: 1
      minutes: 0
      seconds: 0
  conditions: []
  actions:
  - action: notify.mobile_app_pixel_10_pro_xl
    metadata: {}
    data:
      message: Attention Congélateur Miele ne consomme plus depuis 1h
  - action: notify.mobile_app_ipad
    metadata: {}
    data:
      message: Attention le congélateur Miele ne consomme plus depuis 1h
  mode: single
